spring.application.name=DeployPratikum2

DATABASE_URL=jdbc:mysql://localhost:3309/spring
DATABASE_USERNAME=root
DATABASE_PASSWORD=15975321dny

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Allow serving static content
spring.web.resources.static-locations=classpath:/static/
